type SoundProject = {
  id: number;
  title: string;
  role: string;
  category: string;
  image?: string;
  videoUrl?: string;
};

const soundDesignProjects: SoundProject[] = [
  {
    id: 1,
    title: "All I Ever Wanted (Emmy Winner)",
    role: "Composer / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    videoUrl: "https://www.youtube.com/embed/WFcoxtnKlDA",
  },
  {
    id: 2,
    title: "Chavorrucos (Amazon Prime)",
    role: "Composer / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    videoUrl: "https://www.youtube.com/embed/jCj8lh91Yo4",
  },
  {
    id: 3,
    title: "Culpables",
    role: "Composer / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    videoUrl: "https://www.youtube.com/embed/SSNoTTO0Vfo",
  },
  {
    id: 4,
    title: "Despedida de soltera",
    role: "Composer / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    videoUrl: "https://www.youtube.com/embed/BhmlR9XB8FE",
  },
  {
    id: 5,
    title: "El río del perro",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/el-rio-del-perro.jpg",
  },
  {
    id: 6,
    title: "Familia de tres",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/familia-de-tres.jpg",
  },
  {
    id: 7,
    title: "Hasta la raíz",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/hasta-la-raiz.jpg",
  },
  {
    id: 8,
    title: "La caja de los secretos",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/la-caja-de-los-secretos.jpg",
  },
  {
    id: 9,
    title: "La casa de los famosos All Stars",
    role: "Sound Design / Stereo Mix",
    category: "Cine & TV",
    image: "/sounddesign/la-casa-de-los-famosos-all-stars.jpg",
  },
  {
    id: 10,
    title: "La llamada",
    role: "Sound Design / Dolby Atmos Mix",
    category: "Cine & TV",
    image: "/sounddesign/la-llamada.jpg",
  },
  {
    id: 11,
    title: "La última visita",
    role: "Sound Design / Dolby Atmos Mix",
    category: "Cine & TV",
    image: "/sounddesign/la-ultima-visita.jpg",
  },
  {
    id: 12,
    title: "Lo tomas o lo dejas",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/lo-tomas-o-lo-dejas.jpg",
  },
  {
    id: 13,
    title: "Los 50",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/los-50.jpg",
  },
  {
    id: 14,
    title: "Melbo",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/melbo.jpg",
  },
  {
    id: 15,
    title: "Opa Popa Dupa (Temporadas 1–4) (Emmy Nominee) (Disney Plus)",
    role: "Head of Audio / Music Supervisor / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    videoUrl: "https://www.youtube.com/embed/5hN03u9muEg",
  },
  {
    id: 16,
    title: "See you Later",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/see-you-later.jpg",
  },
  {
    id: 17,
    title: "Step 9",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/step-9.jpg",
  },
  {
    id: 18,
    title: "Take it Away",
    role: "Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/take-it-away.jpg",
  },
  {
    id: 19,
    title: "Va por Diego (Cannes World Winner)",
    role: "Composer / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    videoUrl: "https://www.youtube.com/embed/R2zsCNMYETM",
  },
  {
    id: 20,
    title: "Vence a las estrellas",
    role:
      "Head of Audio / Music Supervisor / Sound Design / Stereo Mix",
    category: "Cine & TV",
    image: "/sounddesign/vence-a-las-estrellas.jpg",
  },
  {
    id: 21,
    title: "World Justice Project - Justicia para sanar",
    role: "Composer / Sound Design / 5.1 Mix",
    category: "Cine & TV",
    image: "/sounddesign/wjp-mediacion-indigena.jpg",
  },
  {
    id: 40,
    title: "Cami - Mia (Latin Grammy nominee)",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/ufNX6stOGUY",
  },
  {
    id: 41,
    title: "Carin Leon & Alejandro Fernandez - Me está doliendo",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/2fzU6ZjLQDA",
  },
  {
    id: 42,
    title: "50 Cent Phantom",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/NFadrSVNOKE",
  },
  {
    id: 43,
    title: "Danna Paola - Childstar Trailer",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/UovowLzcJ1w",
  },
  {
    id: 44,
    title: "Danna Paola & Sebastian Yatra - No bailes sola",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/K4UfCkTVYdY",
  },
  {
    id: 45,
    title: "Ha*Ash & Elena Rose - Por ti",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/Pfwb8XuBArQ",
  },
  {
    id: 46,
    title: "Leon Larregui - Locos",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/SXcFYnHSG08",
  },
  {
    id: 47,
    title: "Los Amigos Invisibles - Me espera",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/ZSpSMI1Ea9o",
  },
  {
    id: 48,
    title: "Morat & Jay Wheeler - Sin ti",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/TJSZGoS_YFg",
  },
  {
    id: 49,
    title: "Tony Dize - Quisiera",
    role: "Intro - Outro Music / Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/Md3a3-V4pLw",
  },
  {
    id: 50,
    title: "Tony Dize - Sin GPS",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/qDIPwPle4og",
  },
  {
    id: 51,
    title: "Tony Dize - Un tequila más",
    role: "Sound Design / Mix",
    category: "Videoclips",
    videoUrl: "https://www.youtube.com/embed/YTvd0w-Sx0A",
  },
  {
    id: 60,
    title: "Buchannans",
    role: "Sound Design / Mix",
    category: "Advertising",
    videoUrl: "https://player.vimeo.com/video/174827511",
  },
  {
    id: 61,
    title: "La Carta",
    role: "Composer / Sound Design / Mix",
    category: "Advertising",
    videoUrl: "https://player.vimeo.com/video/442159586",
  },
  {
    id: 62,
    title: "Hit BlackOut",
    role: "Composer / Sound Design / Mix",
    category: "Advertising",
    videoUrl: "https://player.vimeo.com/video/12285593",
  },
  {
    id: 63,
    title: "Hit Conquista",
    role: "Composer / Sound Design / Mix",
    category: "Advertising",
    videoUrl: "https://player.vimeo.com/video/12285724",
  },
  {
    id: 64,
    title: "Dish - Mundial",
    role: "Composer / Sound Design / Mix",
    category: "Advertising",
    videoUrl: "https://player.vimeo.com/video/997077530",
  },
  {
    id: 30,
    title: "Diablo IV Teaser - Abuelo",
    role: "Sound Design / Mix",
    category: "Video Game",
    videoUrl: "https://www.youtube.com/embed/OIcLmYzJtqY?start=1",
  },
  {
    id: 31,
    title: "Diablo IV Teaser - Abuela",
    role: "Sound Design / Mix",
    category: "Video Game",
    videoUrl: "https://www.youtube.com/embed/xeQGakCqAFA",
  },
];

export default soundDesignProjects;
